export interface ReferenceProject {
  id: string;
  title: string;
  imageSrc: string;
  href: string;
  tags: string[];
  year: string;
}

export const referenceProjects: ReferenceProject[] = [
  {
    id: 'visa-ceska-sporitelna',
    title: 'VISA\nČeská spořitelna',
    imageSrc: '/images/reference/visa-ceska-sporitelna.png',
    href: 'https://youtu.be/N0g7knzqBlM?si=WHxbhXjhdmZk9tr5',
    tags: ['Reklamy'],
    year: '2024',
  },
  {
    id: 'skoda',
    title: 'ŠKODA',
    imageSrc: '/images/reference/skoda.jpg',
    href: 'https://www.youtube.com/watch?v=P_S0HjMcG54',
    tags: ['Reklamy', 'Průmysl'],
    year: '2025',
  },
  {
    id: 'oktagon',
    title: 'OKTAGON',
    imageSrc: '/images/reference/oktagon.png',
    href: 'https://youtu.be/C4c6BVEJDEo?si=hoKrdzA9ojyYNIf-',
    tags: ['Sport', 'Eventy'],
    year: '2024',
  },
  {
    id: 'rock-for-people',
    title: 'ROCK FOR PEOPLE',
    imageSrc: '/images/reference/rock-for-people.jpg',
    href: 'https://youtu.be/kT0gNFYKqxU?si=z-WAOQTtlOIXtcIj',
    tags: ['Eventy'],
    year: '2025',
  },
  {
    id: 'darkshire-2024',
    title: 'DARKSHIRE 2024',
    imageSrc: '/images/reference/darkshire-2024.jpg',
    href: 'https://youtu.be/eshETrOsaSA?si=xfIparQFlUcgOcVH',
    tags: ['Eventy'],
    year: '2025',
  },
  {
    id: 'dji',
    title: 'DJI',
    imageSrc: '/images/reference/dji.jpg',
    href: 'https://youtu.be/QlWHwiuOrKA?si=goaaSe1DUJ4EqMBS',
    tags: ['Reklamy'],
    year: '2025',
  },
  {
    id: 'let-it-roll',
    title: 'Let It Roll',
    imageSrc: '/images/reference/let-it-roll.jpg',
    href: 'https://youtu.be/N-ryDTOBHFI?si=ZWhwLiC0z6pWFQbr',
    tags: ['Eventy'],
    year: '2023',
  },
  {
    id: 'franz-josef-kaiser',
    title: 'FRANZ JOSEF KAISER',
    imageSrc: '/images/reference/franz-josef-kaiser.jpg',
    href: 'https://youtu.be/Yzjo0vu__Jw?si=9PoAG-E5EWz7-x4f',
    tags: ['Reklamy'],
    year: '2025',
  },
  {
    id: 'fortuna',
    title: 'FORTUNA',
    imageSrc: '/images/reference/fortuna.jpg',
    href: 'https://www.youtube.com/watch?v=hCDZCdqkRbs',
    tags: ['Reklamy', 'Sport'],
    year: '2025',
  },
  {
    id: 'muni',
    title: 'MUNI',
    imageSrc: '/images/reference/muni.jpg',
    href: 'https://www.youtube.com/watch?v=3A9FmPcQk6Y',
    tags: ['Reklamy'],
    year: '2023',
  },
  {
    id: 'rolls-royce',
    title: 'ROLLS-ROYCE',
    imageSrc: '/images/reference/rolls-royce.jpg',
    href: 'https://www.rollsroyceprague.cz',
    tags: ['Reklamy'],
    year: '2025',
  },
  {
    id: 'hopi-holding',
    title: 'HOPI HOLDING',
    imageSrc: '/images/reference/hopi-holding.jpg',
    href: 'https://youtu.be/fxrfRaArm_Y?si=lyHBA0cIqXhQ-K0k',
    tags: ['Průmysl', 'Reklamy'],
    year: '2025',
  },
  {
    id: 'fortuna-2',
    title: 'FORTUNA',
    imageSrc: '/images/reference/fortuna.png',
    href: 'https://youtu.be/wM8p7A8w5ug',
    tags: ['Reklamy', 'Sport'],
    year: '2023',
  },
  {
    id: 'zapa-beton',
    title: 'ZAPA BETON',
    imageSrc: '/images/reference/zapa-beton.png',
    href: 'https://vimeo.com/showcase/5065458?video=1152213082',
    tags: ['Průmysl'],
    year: '2026',
  },
  {
    id: 'raben',
    title: 'RABEN',
    imageSrc: '/images/reference/raben.jpg',
    href: 'https://youtu.be/QqdW3Tk30E4?si=VBRbuDqDkKzQlx23',
    tags: ['Průmysl'],
    year: '2025',
  },
  {
    id: 'albion-cars',
    title: 'ALBION CARS',
    imageSrc: '/images/reference/albion-cars.png',
    href: 'https://youtu.be/mcUa3GXXGdU',
    tags: ['Reklamy'],
    year: '2023',
  },
  {
    id: 'l-etape',
    title: 'L\'Étape',
    imageSrc: '/images/reference/l-etape.jpg',
    href: 'https://fb.watch/y7dRuhUO8T/',
    tags: ['Sport', 'Eventy'],
    year: '2025',
  },
  {
    id: 'velka-pardubicka',
    title: 'Velká pardubická',
    imageSrc: '/images/reference/velka-pardubicka.png',
    href: 'https://youtu.be/4jYTT2jlvLc?si=KnB2kIYLW6Mzlk7V',
    tags: ['Sport', 'Eventy'],
    year: '2026',
  },
  {
    id: 'investicni-podcast-j-t-banka',
    title: 'investiční podcast\nJ&T Banka',
    imageSrc: '/images/reference/investicni-podcast-j-t-banka.jpg',
    href: 'https://youtu.be/YzE7u0GTtow?si=sH2FkOPUeBADNdYM',
    tags: ['Reklamy'],
    year: '2023',
  },
  {
    id: 'jungheinrich',
    title: 'JUNGHEINRICH',
    imageSrc: '/images/reference/jungheinrich.png',
    href: 'https://youtu.be/vIgBjFqyanM',
    tags: ['Průmysl'],
    year: '2023',
  },
  {
    id: 'triton',
    title: 'TRITON',
    imageSrc: '/images/reference/triton.jpg',
    href: 'https://youtu.be/Aj_0Rtm4rng?si=Tl-MYTqNhpQu9793',
    tags: ['Průmysl', 'Reklamy'],
    year: '2023',
  },
  {
    id: 're-max',
    title: 'RE/MAX',
    imageSrc: '/images/reference/re-max.jpg',
    href: 'https://youtu.be/UNhzcrcD_ck',
    tags: ['Reality', 'Reklamy'],
    year: '2022',
  },
  {
    id: 'cybertruck',
    title: 'CYBERTRUCK',
    imageSrc: '/images/reference/cybertruck.jpg',
    href: 'https://youtu.be/cZcCs-sRhvk?si=xDocQUpVu_zxyWJi',
    tags: ['Reklamy'],
    year: '2025',
  },
  {
    id: 'chalet-astre',
    title: 'CHALET ASTRÉ',
    imageSrc: '/images/reference/chalet-astre.jpg',
    href: 'https://youtu.be/EsSNbYIeDSQ',
    tags: ['Reality'],
    year: '2022',
  },
  {
    id: 'nordic-telecom',
    title: 'Nordic telecom',
    imageSrc: '/images/reference/nordic-telecom.jpg',
    href: 'https://youtu.be/VuqwKG82UsQ',
    tags: ['Reklamy'],
    year: '2022',
  },
  {
    id: 'pepsi',
    title: 'PEPSI',
    imageSrc: '/images/reference/pepsi.jpg',
    href: 'https://youtu.be/KHiboX409VY',
    tags: ['Reklamy'],
    year: '2022',
  },
  {
    id: 'direct-auto',
    title: 'DIRECT AUTO',
    imageSrc: '/images/reference/direct-auto.jpg',
    href: 'https://youtu.be/ga4GGwBlTNE?si=wigMmQWopSwGNw3n',
    tags: ['Reklamy'],
    year: '2025',
  },
  {
    id: 'bikefest',
    title: 'BIKEFEST',
    imageSrc: '/images/reference/bikefest.png',
    href: 'https://youtu.be/sQmxxbo1b5o?si=Y6jaLfxC4jICiVc-',
    tags: ['Eventy', 'Sport'],
    year: '2024',
  },
  {
    id: 'sazka',
    title: 'SAZKA',
    imageSrc: '/images/reference/sazka.jpg',
    href: 'https://youtu.be/FZHe-QUCe4I',
    tags: ['Reklamy'],
    year: '2022',
  },
  {
    id: 'quix',
    title: 'QUIX',
    imageSrc: '/images/reference/quix.jpg',
    href: 'https://www.youtube.com/watch?v=xmjsIzLZ6Lo',
    tags: ['Reklamy', 'Sport'],
    year: '2023',
  },
  {
    id: 'next-move',
    title: 'Next Move.',
    imageSrc: '/images/reference/next-move.jpg',
    href: 'https://youtu.be/WH6GgqCxClU',
    tags: ['Reklamy'],
    year: '2022',
  },
  {
    id: 'aikido-street-story',
    title: 'Aikido - Street Story',
    imageSrc: '/images/reference/aikido-street-story.jpg',
    href: 'https://youtu.be/YG3zw5FRJ-Y',
    tags: ['Sport'],
    year: '2022',
  },
  {
    id: 'bednar',
    title: 'BEDNAR',
    imageSrc: '/images/reference/bednar.jpg',
    href: 'https://www.youtube.com/watch?v=gjaJEkH4DXE',
    tags: ['Průmysl'],
    year: '2023',
  },
  {
    id: 'harvestlove',
    title: 'HarvestLove',
    imageSrc: '/images/reference/harvestlove.jpg',
    href: 'https://www.youtube.com/watch?v=nwSEIhxPK40&t=78s',
    tags: ['Eventy'],
    year: '2023',
  },
  {
    id: 'svet-motoru',
    title: 'SVĚT MOTORŮ',
    imageSrc: '/images/reference/svet-motoru.jpg',
    href: 'https://youtu.be/e96dXhpffc8?si=_Te790SNfwoD3-Cv',
    tags: ['Reklamy'],
    year: '2023',
  },
  {
    id: 'cesky-kralovsky-institut',
    title: 'Český královský institut',
    imageSrc: '/images/reference/cesky-kralovsky-institut.jpg',
    href: 'https://youtu.be/29Wn-LFA_TQ',
    tags: ['Eventy'],
    year: '2022',
  },
  {
    id: 'idm-livestream',
    title: 'IDM\nlivestream',
    imageSrc: '/images/reference/idm-livestream.jpg',
    href: 'https://www.youtube.com/live/KThu6SfipIM?si=yn3ZGKxQQIiND5kW',
    tags: ['Eventy', 'Livestream'],
    year: '2023',
  },
  {
    id: 'leswood',
    title: 'LESWOOD',
    imageSrc: '/images/reference/leswood.jpg',
    href: 'https://www.youtube.com/watch?v=ICFaRVpe2tU',
    tags: ['Průmysl'],
    year: '2023',
  },
  {
    id: 'smack-one-kazdej-z-vas',
    title: 'Smack One\nKaždej Z Vás',
    imageSrc: '/images/reference/smack-one-kazdej-z-vas.jpg',
    href: 'https://youtu.be/qLtc-0bDR_Y?si=kgg8Cj8CcE5GI4ZF',
    tags: ['Videoklipy'],
    year: '2023',
  },
  {
    id: 'eva-buresova-slzy',
    title: 'Eva Burešová \nSlzy',
    imageSrc: '/images/reference/eva-buresova-slzy.png',
    href: 'https://youtu.be/HRHX7cQb8hA?si=IcFV3YOA4qa2Bion',
    tags: ['Videoklipy'],
    year: '2024',
  },
  {
    id: 'renne-dang-nalady-a-vykyvy',
    title: 'Renne Dang \nNálady a Výkyvy',
    imageSrc: '/images/reference/renne-dang-nalady-a-vykyvy.jpg',
    href: 'https://youtu.be/mPhraZ6VeWw',
    tags: ['Videoklipy'],
    year: '2022',
  },
  {
    id: 'erne100-transport',
    title: 'ERNE100\nTRANSPORT',
    imageSrc: '/images/reference/erne100-transport.jpg',
    href: 'https://youtu.be/gTvwoKZDlog?si=kaJMxTPbXOKWEdkt',
    tags: ['Videoklipy'],
    year: '2023',
  },
  {
    id: 'orion-cistychov-2-chudacci',
    title: 'Orion & Čistychov\n2 Chudáčci',
    imageSrc: '/images/reference/orion-cistychov-2-chudacci.jpg',
    href: 'https://youtu.be/3iMdEWmydkI?si=KrLTcasnIzcsELBB',
    tags: ['Videoklipy'],
    year: '2025',
  },
  {
    id: 'tomba-ft-paulie-garand',
    title: 'Tomba\nft. Paulie Garand',
    imageSrc: '/images/reference/tomba-ft-paulie-garand.jpg',
    href: 'https://youtu.be/yuQq-n9C7mc?si=3rNG65kPMSr61_1F',
    tags: ['Videoklipy'],
    year: '2023',
  },
  {
    id: 'jay-diesel-balanc',
    title: 'Jay Diesel\nBALANC',
    imageSrc: '/images/reference/jay-diesel-balanc.jpg',
    href: 'https://youtu.be/qkhqynvofZI',
    tags: ['Videoklipy'],
    year: '2022',
  },
  {
    id: 'cerny-zaludi-cauve-cuco',
    title: 'Černý žaludi\nČauve Čůčo',
    imageSrc: '/images/reference/cerny-zaludi-cauve-cuco.jpg',
    href: 'https://youtu.be/38ACyxLJOx8',
    tags: ['Videoklipy'],
    year: '2022',
  },
  {
    id: 'jakub-k-nig-zpravy',
    title: 'Jakub König\nZprávy',
    imageSrc: '/images/reference/jakub-k-nig-zpravy.png',
    href: 'https://youtu.be/7Zqh5Km_fxo?si=E3x3kwxExsqwYhw9',
    tags: ['Videoklipy'],
    year: '2026',
  },
  {
    id: 'silly-vlastni-uroven',
    title: 'SIllY\nVlastní Úroveň',
    imageSrc: '/images/reference/silly-vlastni-uroven.jpg',
    href: 'https://youtu.be/jdhYr0xKoaQ',
    tags: ['Videoklipy'],
    year: '2022',
  },
];
